// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SassCompiler
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSassCompilerPackageString = "364bd1cf-2c06-490d-8aa4-b50163e28d3c";
        public static Guid guidSassCompilerPackage = new Guid(guidSassCompilerPackageString);

        public const string guidSassUIRuleString = "e123a225-e3c4-4a68-b7a2-58dc52a4f709";
        public static Guid guidSassUIRule = new Guid(guidSassUIRuleString);

        public const string guidSassCompilerPackageCmdSetString = "be6ceda4-9855-4f0f-99c8-fcc5bfa83b6c";
        public static Guid guidSassCompilerPackageCmdSet = new Guid(guidSassCompilerPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CustomToolCommandId = 0x0100;
    }
}