// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SassCompiler
{
    internal sealed partial class Vsix
    {
        public const string Id = "SassCompiler.51aaf69f-7f00-426c-a697-64a2b5acabc3";
        public const string Name = "Sass Compiler";
        public const string Description = @"Transpiles Sass/Scss files to CSS and minifies it instantly - every time you save the file";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
